### ISSUE TITLE
Over level 15 

### ISSUE THREAD

**Issue by eggplants** [ContentsViewer/sh-tetris#44]
Previously, the level raised up to 16 when I accomplish the goal lines in level 15.
But now:

![image](https://user-images.githubusercontent.com/42153744/147390477-f9adc118-1204-4893-845e-fb82b5406504.png)

**Comment by ko1nksm** [comment]
This was fixed by me in #31.

In previous versions, the maximum Level was 16, but the maximum speed defined is Level 15, so I think it is a bug. The behavior when the goal of level 15 is reached, we will need to define the specifications. There are some implementations that will end the game, but I want to continue the game.

So I propose a specification where the speed is maxed out at level 15, but the level continues to increase indefinitely. Of course, this specification can be changed as the game grows. What do you think? If you agree with this specification, I would like to implement it.

**Comment by eggplants** [comment]
> So I propose a specification where the speed is maxed out at level 15, but the level continues to increase indefinitely.

I agree. But @ContentsViewer -san makes final decision.

**Comment by eggplants** [comment]
At least, `GOAL 600` is wrong. It should be `GOAL inf`, `GOAL ∞` or `GOAL ---`

**Comment by ContentsViewer** [comment]
It is related with new game mode feature, so let's decide how to implement it before next release (v2.3.0?).
